# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Employee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Employee

	pod 'SwiftyJSON', '~> 4.0.0'
  	pod 'Moya', '~> 14.0.0'

  target 'EmployeeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EmployeeUITests' do
    # Pods for testing
  end

end
